// Generated by gencpp from file ur_rtde_msgs/JointVoltages.msg
// DO NOT EDIT!


#ifndef UR_RTDE_MSGS_MESSAGE_JOINTVOLTAGES_H
#define UR_RTDE_MSGS_MESSAGE_JOINTVOLTAGES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur_rtde_msgs
{
template <class ContainerAllocator>
struct JointVoltages_
{
  typedef JointVoltages_<ContainerAllocator> Type;

  JointVoltages_()
    : data()  {
    }
  JointVoltages_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::ur_rtde_msgs::JointVoltages_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur_rtde_msgs::JointVoltages_<ContainerAllocator> const> ConstPtr;

}; // struct JointVoltages_

typedef ::ur_rtde_msgs::JointVoltages_<std::allocator<void> > JointVoltages;

typedef boost::shared_ptr< ::ur_rtde_msgs::JointVoltages > JointVoltagesPtr;
typedef boost::shared_ptr< ::ur_rtde_msgs::JointVoltages const> JointVoltagesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur_rtde_msgs::JointVoltages_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur_rtde_msgs::JointVoltages_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur_rtde_msgs::JointVoltages_<ContainerAllocator1> & lhs, const ::ur_rtde_msgs::JointVoltages_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur_rtde_msgs::JointVoltages_<ContainerAllocator1> & lhs, const ::ur_rtde_msgs::JointVoltages_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur_rtde_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ur_rtde_msgs::JointVoltages_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur_rtde_msgs::JointVoltages_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_rtde_msgs::JointVoltages_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_rtde_msgs::JointVoltages_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_rtde_msgs::JointVoltages_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_rtde_msgs::JointVoltages_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur_rtde_msgs::JointVoltages_<ContainerAllocator> >
{
  static const char* value()
  {
    return "788898178a3da2c3718461eecda8f714";
  }

  static const char* value(const ::ur_rtde_msgs::JointVoltages_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x788898178a3da2c3ULL;
  static const uint64_t static_value2 = 0x718461eecda8f714ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur_rtde_msgs::JointVoltages_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur_rtde_msgs/JointVoltages";
  }

  static const char* value(const ::ur_rtde_msgs::JointVoltages_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur_rtde_msgs::JointVoltages_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message holds data to describe the voltages of all robot joints.\n"
"\n"
"float64[] data\n"
;
  }

  static const char* value(const ::ur_rtde_msgs::JointVoltages_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur_rtde_msgs::JointVoltages_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointVoltages_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur_rtde_msgs::JointVoltages_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur_rtde_msgs::JointVoltages_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR_RTDE_MSGS_MESSAGE_JOINTVOLTAGES_H
