(cl:in-package ur_rtde_msgs-msg)
(cl:export '(IS_NORMAL_MODE-VAL
          IS_NORMAL_MODE
          IS_REDUCED_MODE-VAL
          IS_REDUCED_MODE
          IS_PROTECTIVE_STOPPED-VAL
          IS_PROTECTIVE_STOPPED
          IS_RECOVERY_MODE-VAL
          IS_RECOVERY_MODE
          IS_SAFEGUARD_STOPPED-VAL
          IS_SAFEGUARD_STOPPED
          IS_SYSTEM_EMERGENCY_STOPPED-VAL
          IS_SYSTEM_EMERGENCY_STOPPED
          IS_ROBOT_EMERGENCY_STOPPED-VAL
          IS_ROBOT_EMERGENCY_STOPPED
          IS_EMERGENCY_STOPPED-VAL
          IS_EMERGENCY_STOPPED
          IS_VIOLATION-VAL
          IS_VIOLATION
          IS_FAULT-VAL
          IS_FAULT
          IS_STOPPED_DUE_TO_SAFETY-VAL
          IS_STOPPED_DUE_TO_SAFETY
))